name: Generate snake animation

on:
  schedule:
    - cron: "0 0 * * *"   # 每天 UTC 时间 0 点自动运行，保持更新
  workflow_dispatch:      # 允许你手动在 Actions 页面触发
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write     # 授予写入权限，用于推送生成的图片
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: generate snake.svg
      uses: Platane/snk@v3   # 使用核心工具 snk
      with:
        github_user_name: ${{ github.repository_owner }}
        # 定义输出的文件。可以生成不同主题的 SVG 或 GIF
        outputs: |
          dist/github-snake.svg
          dist/github-snake-dark.svg?palette=github-dark

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v4
      with:
        target_branch: output   # 将生成的图片推送到独立的 output 分支
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
